name: 'cargo-checkmate'
description: 'Run cargo-checkmate on a rust crate'
inputs:
  phase:
    description: 'The cargo-checkmate phase to run'
    required: false
    default: 'all'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/cargo-checkmate/action:latest'
  args:
    - ${{ inputs.phase }}
